### ISSUE TITLE
DISCORD_ONCONNECTNOTICE: false not working

### ISSUE THREAD

**Issue by kaaac** [VAMSApp/OnAirDiscordBot#14]
Bot sends message to channel ignoring settings to not sent welcome message:
docker-compose:
```
services:
  bot:
    image: mikedevita/onairdiscordbot
    container_name: onairdiscordbot
    restart: always
    environment:
      DISCORD_TOKEN: 'Redacted'
      DISCORD_CLIENTID: 'Redacted'
      DISCORD_GUILDID: 'Redacted'
      DISCORD_OWNER: 'Redacted' #switch owner
      DISCORD_CHANNEL: 'Redacted' #switch server
      DISCORD_DEPLOYCOMMANDS: 'true'
      DISCORD_ONCONNECTNOTICE: 'false'
      ONAIR_COMPANYID: 'Redacted'
      ONAIR_VAID: 'Redacted'
      ONAIR_APIKEY: 'Redacted'
      LOGLEVEL: 'info'
      LOG_TO_CONSOLE: 'true'
      
```
